ci: test for preprod release 2

diff --git a/.github/workflows/preprod.yml b/.github/workflows/preprod.yml
--- a/.github/workflows/preprod.yml
+++ b/.github/workflows/preprod.yml
@@ -33,6 +33,10 @@ jobs:
       - name: Build project
         run: pnpm build
 
+      - name: Debug fetch tags
+        run: |
+          git fetch --tags || (echo "Failed to fetch tags" && exit 1)
+
       - name: Tag version
         id: tag_version
         run: |
